[package]
name = "blog_os"
version = "0.1.0"
authors = ["Chang Chen Chien <e850506@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
